### ISSUE TITLE
Project folder structure

### ISSUE THREAD

**Issue by thomrick** [marcinwysocki/nestjs-typescript-boilerplate#2]
Can't generate assets (component, module, controller...) 
In fact the minimum structure to use the CLI tool is:
```text
src
 |
 ----- app
        |
        ------ app.module.(ts|js)
```

**Comment by marcinwysocki** [comment]
Thanks, I've changed the folder structure to reflect this (680ad2c243219458839cb1077c2c590fa36404d9).
